### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by kevsully** [alexverboon/posh#1]
Hi Alex, I love what you are doing here, great stuff. My comments are my opinion based on my experiences and as I am constantly learning these opinions represent a moment in time. 
1. Using WS-MAN vs. RPC for PowerShell remoting is likely a most standard an future proof approach.
2. Use common parameter names for consistency with other cmdlets. The GroupPolicy module did not follow standards as well as some others. (-Computer vs. -ComputerName)
3. I'm not sure of the install routine. Do you think this is required?
4. Use full cmdlet names in module and help content... Get-Command vs. gcm... better form IMO.

Kevin

**Comment by alexverboon** [comment]
Hi Kevin
Many thanks for the feedback, really appreciate it. I will take your inputs into consideration when making further updates.

As for the install/update routine, i wanted to make it as simple as posible for others to start using the module.
Regards
Alex
